name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  firebase_messaging: ^16.1.2
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- ESTE BLOQUE SOLO DEBE APARECER UNA VEZ ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F26B2A" 
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#F26B2A"
  image: assets/logo.png 
  fullscreen: true
  
  android_12:
    color: "#F26B2A"
    image: assets/logo.png
    