// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsUC_CNsc_bH4mSyslNz4mBNILtmLVD_w',
    appId: '1:652891876768:web:044ba66675457e562348c5',
    messagingSenderId: '652891876768',
    projectId: 'delazona',
    authDomain: 'delazona.firebaseapp.com',
    storageBucket: 'delazona.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC4pEIVSmmHmSaTw1GVEn354zLG6HThm0',
    appId: '1:652891876768:android:a7f18c40575ecac52348c5',
    messagingSenderId: '652891876768',
    projectId: 'delazona',
    storageBucket: 'delazona.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXuqXcUq8uek3PqM9JzhYWKQgH-EFSido',
    appId: '1:652891876768:ios:4c48be0de9eac3882348c5',
    messagingSenderId: '652891876768',
    projectId: 'delazona',
    storageBucket: 'delazona.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXuqXcUq8uek3PqM9JzhYWKQgH-EFSido',
    appId: '1:652891876768:ios:4c48be0de9eac3882348c5',
    messagingSenderId: '652891876768',
    projectId: 'delazona',
    storageBucket: 'delazona.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsUC_CNsc_bH4mSyslNz4mBNILtmLVD_w',
    appId: '1:652891876768:web:b250a231e71f37332348c5',
    messagingSenderId: '652891876768',
    projectId: 'delazona',
    authDomain: 'delazona.firebaseapp.com',
    storageBucket: 'delazona.firebasestorage.app',
  );
}
